# Generated by Django 3.2.3 on 2021-06-04 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("projects", "0001_initial"),
        ("projects", "0002_delete_projectsconfig"),
    ]

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="",
                        max_length=100,
                        unique=True,
                        verbose_name="Project Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="",
                        help_text="Write in Markdown format",
                        verbose_name="Project Description",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Project URL")),
                (
                    "order",
                    models.IntegerField(
                        help_text="Projects are ordered by this number (from smallest to largest).<br><strong>No duplicates allowed.</strong>",
                        unique=True,
                        verbose_name="Sort order",
                    ),
                ),
                (
                    "embed",
                    models.ForeignKey(
                        blank=True,
                        help_text="If both are selected, only embedded media will show on screen.<br><strong>When printing, only image will show.</strong>",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media.embed",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="If both are selected, only embedded media will show on screen.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media.image",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
    ]
