# Generated by Django 3.1.1 on 2020-09-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsconfig',
            name='description',
        ),
    ]
