# Generated by Django 3.1.7 on 2021-02-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectsConfig',
        ),
    ]
