# Generated by Django 2.2 on 2019-04-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_description',
            field=models.CharField(blank=True, default='View Project', max_length=50, verbose_name='URL Label'),
        ),
    ]
