# Generated by Django 3.1.3 on 2020-11-12 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('projects', '0002_remove_projectsconfig_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'title']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='posted',
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='Projects are ordered by this number (from smallest to largest).<br><strong>No duplicates allowed.</strong>', unique=True, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='embed',
            field=models.ForeignKey(blank=True, help_text='If both are selected, only embedded media will show on screen.<br><strong>When printing, only image will show.</strong>', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.embed'),
        ),
    ]
