# Generated by Django 2.2 on 2019-04-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190413_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fa_icon',
        ),
    ]
