# Generated by Django 5.2.16 on 2026-07-26 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial_squashed_0002_delete_projectsconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("order", "title")},
        ),
    ]
