# Generated by Django 3.1.3 on 2020-11-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201112_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(help_text='Projects are ordered by this number (from smallest to largest).<br><strong>No duplicates allowed.</strong>', null=True, unique=True, verbose_name='Sort order'),
        ),
    ]
