# Generated by Django 2.2.2 on 2019-06-26 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_url_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='embed',
            field=models.ForeignKey(blank=True, help_text='<strong>When printing, only image will show.</strong><br>If both are selected, only embedded media will show on screen.', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Embed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, help_text='If both are selected, only embedded media will show on screen.', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Image'),
        ),
    ]
