os: linux
dist: bionic

jobs:
  include:
    - stage: test
      if: branch != master
      language: python
      python: 3.8
      install:
        - cp example.env .env
        - pip install -r requirements.txt
      script:
        - python3 manage.py migrate --run-syncdb
        - python3 manage.py test
    - stage: build and test docker image
      if: branch = master
      env: DOCKER_REPO=chrisx8/simple-personal-site:latest
      language: minimal
      services:
        - docker
      install:
        - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` -t $DOCKER_REPO .
      script:
        - docker run -p 127.0.0.1:8000:8000 --env-file example.env "$DOCKER_REPO" &
        - sleep 5
        - curl -Lf localhost:8000
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_REPO
