dist: bionic
language: minimal
sudo: required
cache:
  directories:
    - docker_images
env:
  - DOCKER_REPO=chrisx8/simple-personal-site:latest
services:
  - docker

before_install:
  - docker load -i docker_images/images.tar || true
  
before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)

install:
  - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` -t $DOCKER_REPO . || travis_terminate 1
      
script:
  - docker run -p 127.0.0.1:8000:8000 --env-file config.example.env "$DOCKER_REPO" &
  - sleep 5
  - curl -Lf localhost:8000 || travis_terminate 1

deploy:
  on:
    branch: master
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_REPO
