sudo: required
language: minimal
services:
  - docker
install:
  - docker build -t $DOCKER_REPO .
script:
  - docker run --env-file site_config.example.env $DOCKER_REPO python manage.py migrate
  - docker run --env-file site_config.example.env $DOCKER_REPO python manage.py test
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_REPO
