dist: bionic

jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.8"
      cache: pip      
      install:
        - cp config.example.env config.env
        - pip install -r requirements.txt
        - cp $HOME/.cache/pip/site.db site.db | true
      script:
        - python3 manage.py migrate --run-syncdb
        - python3 manage.py test
        - cp site.db $HOME/.cache/pip/site.db
    - stage: build and test docker image
      if: branch = master
      language: minimal
      sudo: required
      services:
        - docker
      env: DOCKER_REPO=chrisx8/simple-personal-site:latest
      script:
        - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` -t $DOCKER_REPO .
        - docker run -p 127.0.0.1:8000:8000 --env-file config.example.env "$DOCKER_REPO" &
        - sleep 5
        - curl -Lf localhost:8000
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_REPO
