dist: xenial
sudo: required
language: python
python:
  - "3.7"
  - "3.6"
cache: 
  - pip
  - directories:
      - site.db
install:
  - cp site_config.example.env site_config.env
  - pip install -r requirements.txt
script:
  - python3 manage.py migrate
  - python3 manage.py test
jobs:
  include:
    - stage: build docker image
      if: branch = master
      env: DOCKER_REPO=chrisx8/simple-personal-site:latest
      script:
        - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_REPO .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_REPO
