# Generated by Django 3.2.9 on 2021-12-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcaptcha_site_key', models.UUIDField(blank=True, help_text='Blank = no captcha on contact form', null=True, verbose_name='hCaptcha Sitekey')),
                ('hcaptcha_secret_key', models.CharField(blank=True, help_text='Blank = no captcha on contact form', max_length=42, verbose_name='hCaptcha secret key')),
                ('from_email', models.EmailField(blank=True, help_text='Blank = no outgoing emails', max_length=254, verbose_name='Email address shown on outgoing emails')),
                ('notification_recipient', models.EmailField(blank=True, help_text='Blank = no notification emails for new messages', max_length=254, verbose_name="Notification recipient's email address")),
            ],
            options={
                'verbose_name': '*Contact Config*',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='(no subject)', max_length=300)),
                ('message', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
