# Generated by Django 3.1.3 on 2020-11-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcaptcha_site_key', models.UUIDField(blank=True, help_text='Blank = no captcha on contact form', null=True, verbose_name='hCaptcha Sitekey')),
                ('hcaptcha_secret_key', models.CharField(blank=True, help_text='Blank = no captcha on contact form', max_length=42, verbose_name='hCaptcha secret key')),
                ('from_name', models.CharField(blank=True, help_text='Blank = no outgoing emails', max_length=50, verbose_name='Name shown on outgoing emails')),
                ('from_email', models.EmailField(blank=True, help_text='Blank = no outgoing emails', max_length=254, verbose_name='Email address shown on outgoing emails')),
                ('notification_recipient', models.EmailField(blank=True, help_text='Blank = no notification emails for new messages', max_length=254, verbose_name="Notification recipient's email address")),
                ('pgp_fingerprint', models.CharField(blank=True, max_length=50, verbose_name='Public key fingerprint')),
                ('pgp_key', models.TextField(blank=True, help_text='Begins with "-----BEGIN PGP PUBLIC KEY BLOCK-----"', verbose_name='Public key')),
            ],
            options={
                'verbose_name': '# Contact Config #',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default='')),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['read', 'timestamp'],
            },
        ),
    ]
