# Generated by Django 3.0.5 on 2020-04-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcaptcha_site_key', models.UUIDField(blank=True, help_text='Leaving blank = no captcha on contact form', null=True, verbose_name='hCaptcha Sitekey')),
                ('hcaptcha_secret_key', models.CharField(blank=True, help_text='Leaving blank = no captcha on contact form', max_length=42, verbose_name='hCaptcha secret key')),
                ('site_owner_email', models.EmailField(blank=True, help_text='Leaving blank = no notification emails to site owner', max_length=254, verbose_name="Site owner's email address.")),
                ('from_name', models.CharField(blank=True, help_text='Leaving blank = no emails', max_length=50, verbose_name='Name shown on outgoing emails')),
                ('from_email', models.EmailField(blank=True, help_text='Leaving blank = no emails', max_length=254, verbose_name='Email address shown on outgoing emails')),
                ('subject', models.CharField(blank=True, help_text='Leaving blank = no emails to message sender', max_length=250, verbose_name='Subject of outgoing emails')),
                ('pgp_fingerprint', models.CharField(blank=True, max_length=50, verbose_name='Public key fingerprint')),
                ('pgp_url', models.URLField(blank=True, verbose_name='Public key URL')),
            ],
            options={
                'verbose_name': '# Contact Config #',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default='')),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['read', 'timestamp'],
            },
        ),
    ]
