# Generated by Django 3.0.3 on 2020-02-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactconfig',
            name='pgp_pubkey',
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='pgp_fingerprint',
            field=models.CharField(blank=True, max_length=50, verbose_name='Public key fingerprint'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='pgp_url',
            field=models.URLField(blank=True, verbose_name='Public key URL'),
        ),
    ]
