# Generated by Django 3.0.6 on 2020-05-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactconfig',
            name='pgp_url',
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='pgp_key',
            field=models.URLField(blank=True, help_text='begins with "-----BEGIN PGP PUBLIC KEY BLOCK-----"', verbose_name='Public key'),
        ),
        migrations.AlterField(
            model_name='contactconfig',
            name='from_email',
            field=models.EmailField(blank=True, help_text='Blank = no emails', max_length=254, verbose_name='Email address shown on outgoing emails'),
        ),
        migrations.AlterField(
            model_name='contactconfig',
            name='from_name',
            field=models.CharField(blank=True, help_text='Blank = no emails', max_length=50, verbose_name='Name shown on outgoing emails'),
        ),
        migrations.AlterField(
            model_name='contactconfig',
            name='hcaptcha_secret_key',
            field=models.CharField(blank=True, help_text='Blank = no captcha on contact form', max_length=42, verbose_name='hCaptcha secret key'),
        ),
        migrations.AlterField(
            model_name='contactconfig',
            name='hcaptcha_site_key',
            field=models.UUIDField(blank=True, help_text='Blank = no captcha on contact form', null=True, verbose_name='hCaptcha Sitekey'),
        ),
        migrations.AlterField(
            model_name='contactconfig',
            name='site_owner_email',
            field=models.EmailField(blank=True, help_text='Blank = no notification emails to site owner', max_length=254, verbose_name="Site owner's email address."),
        ),
        migrations.AlterField(
            model_name='contactconfig',
            name='subject',
            field=models.CharField(blank=True, help_text='Blank = no emails to message sender', max_length=250, verbose_name='Subject of outgoing emails'),
        ),
    ]
