# Generated by Django 2.2 on 2019-04-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='show',
        ),
    ]
