# Generated by Django 2.2.1 on 2019-05-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactconfig',
            name='pgp_pubkey',
            field=models.TextField(blank=True, help_text='Paste your PGP public key here', verbose_name='PGP Public key'),
        ),
    ]
