# Generated by Django 3.1.7 on 2021-02-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactconfig_from_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactconfig',
            options={'verbose_name': '*Contact Config*'},
        ),
    ]
