# Generated by Django 2.2 on 2019-04-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_socialmedialink_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='fa_icon',
        ),
    ]
