# Generated by Django 3.0.6 on 2020-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200508_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactconfig',
            name='pgp_key',
            field=models.TextField(blank=True, help_text='Begins with "-----BEGIN PGP PUBLIC KEY BLOCK-----"', verbose_name='Public key'),
        ),
    ]
