# Generated by Django 3.1.7 on 2021-03-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210222_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
