# Generated by Django 2.2 on 2019-04-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_socialmedialink_fa_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='color',
        ),
    ]
