# Generated by Django 5.2.16 on 2026-07-26 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial_squashed_0005_message_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("-timestamp",)},
        ),
    ]
