# Generated by Django 2.2 on 2019-04-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', help_text='This field sets the Meta Description tag for /blog/. Always followed by "Check out my latest article: TITLE". Leave blank to use global Meta Description tag.', max_length=250)),
                ('articles_per_page', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': '# Blog Config #',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Article ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField(default='', help_text='Write in Markdown')),
                ('last_edited', models.DateField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, help_text='When both image and video are selected, only video will show.', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Image')),
                ('tag', models.ManyToManyField(blank=True, to='blog.Tag')),
                ('video', models.ForeignKey(blank=True, help_text='When both image and video are selected, only video will show.', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Video')),
            ],
            options={
                'ordering': ['-last_edited', 'title'],
            },
        ),
    ]
