# Generated by Django 2.2 on 2019-04-12 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Article ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField(default='', help_text='Write in Markdown')),
                ('show', models.BooleanField(default=True, help_text='Show article on blog')),
                ('time_posted', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, help_text='When both image and video are selected, only video will show.', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Image')),
                ('tag', models.ManyToManyField(blank=True, to='blog.Tag')),
                ('video', models.ForeignKey(blank=True, help_text='When both image and video are selected, only video will show.', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Video')),
            ],
        ),
    ]
