# Generated by Django 3.0.6 on 2020-05-07 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_embed_allow_fullscreen'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ForeignKey(blank=True, help_text='<strong>When printing, only image will show.</strong><br>If both are selected, only embedded media will show on screen.', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Image'),
        ),
    ]
