# Generated by Django 2.2 on 2019-04-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='show',
        ),
        migrations.RemoveField(
            model_name='article',
            name='time_posted',
        ),
    ]
