# Generated by Django 2.2.1 on 2019-05-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190507_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
    ]
