# Generated by Django 2.2 on 2019-04-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190331_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Article ID'),
        ),
    ]
