# Generated by Django 3.1.7 on 2021-02-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210101_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogConfig',
        ),
    ]
