# Generated by Django 3.1.3 on 2020-11-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogconfig_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
