# Generated by Django 5.2.16 on 2026-07-26 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial_squashed_0003_delete_blogconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ("-last_edited", "title")},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("tag",)},
        ),
    ]
