# Generated by Django 2.2 on 2019-04-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, help_text='URL to SMTP server. Leaving blank disables email. <strong>Effective after restart</strong>', max_length=500)),
                ('port', models.IntegerField(blank=True, help_text='Port of SMTP server. Leaving blank disables email. <strong>Effective after restart</strong>', null=True)),
                ('username', models.CharField(blank=True, help_text='SMTP username. Leaving blank disables email. <strong>Effective after restart</strong>', max_length=500)),
                ('password', models.CharField(blank=True, help_text='SMTP password. Leaving blank disables email. <strong>Effective after restart</strong>', max_length=500)),
                ('use_tls', models.BooleanField(default=False, help_text='Do not enable both SSL and TLS. <strong>Effective after restart</strong>', verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, help_text='Do not enable both SSL and TLS. <strong>Effective after restart</strong>', verbose_name='Use SSL')),
            ],
            options={
                'verbose_name': 'Email Config',
            },
        ),
        migrations.CreateModel(
            name='Fathom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathom_url', models.URLField(blank=True, help_text='Full URL to Fathom\'s "tracker.js". Leaving blank disables Fathom.', verbose_name='Fathom URL')),
                ('site_id', models.CharField(blank=True, help_text='Fathom Site ID. Leaving blank disables Fathom', max_length=5, verbose_name='Site ID')),
            ],
            options={
                'verbose_name': 'Fathom Analytics',
            },
        ),
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_tracking_id', models.CharField(blank=True, help_text='Google Analytics Tracking ID. Leaving blank disables Google Analytics', max_length=15, verbose_name='Tracking ID')),
            ],
            options={
                'verbose_name': 'Google Analytics',
            },
        ),
        migrations.CreateModel(
            name='ReCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(blank=True, help_text='Recommended for spam prevention. Leaving blank disables ReCaptcha. <strong>Effective after restart</strong> <a href="https://www.google.com/recaptcha/admin">Get ReCAPTCHA key</a>', max_length=50)),
                ('public_key', models.CharField(blank=True, help_text='Recommended for spam prevention. Leaving blank disables ReCaptcha. <strong>Effective after restart</strong> <a href="https://www.google.com/recaptcha/admin">Get ReCAPTCHA key</a>', max_length=50)),
            ],
            options={
                'verbose_name': 'ReCaptcha v2',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', max_length=50)),
                ('site_url', models.URLField(default='', help_text='Include "http://" or "https://". <strong>Effective after restart</strong>', verbose_name='Site URL')),
                ('description', models.CharField(blank=True, default='', help_text='This field sets the global Meta Description tag.', max_length=250)),
                ('header_title', models.CharField(default='My Site', max_length=250)),
                ('header_subtitle', models.CharField(blank=True, max_length=250)),
                ('footer_copyright', models.CharField(default='Simple Personal Site by @chrisx8.', help_text='"&copy; year " always shows. Set this to be the text after "&copy; year "', max_length=250)),
            ],
            options={
                'verbose_name': '# Site Info #',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='', help_text='Name of the social media platform', max_length=50)),
                ('username', models.CharField(default='', help_text='Omit @ symbol', max_length=100)),
                ('url', models.URLField(default='', help_text='Link to profile page')),
                ('display_at', models.BooleanField(default=False, verbose_name='Display "@" before username')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'ordering': ['platform', 'username'],
            },
        ),
    ]
