# Generated by Django 3.0.2 on 2020-01-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fathom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathom_url', models.URLField(blank=True, help_text='Full URL to Fathom\'s "tracker.js". Leaving blank disables Fathom.', verbose_name='Fathom URL')),
                ('site_id', models.CharField(blank=True, help_text='Fathom Site ID. Leaving blank disables Fathom', max_length=5, verbose_name='Site ID')),
            ],
            options={
                'verbose_name': 'Fathom Analytics',
            },
        ),
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_tracking_id', models.CharField(blank=True, help_text='Google Analytics Tracking ID. Leaving blank disables Google Analytics', max_length=15, verbose_name='Tracking ID')),
            ],
            options={
                'verbose_name': 'Google Analytics',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', max_length=50)),
                ('site_url', models.URLField(default='http://example.com', help_text='Include "http://" or "https://". No trailing slashes. <strong>Effective after restart</strong>', verbose_name='Site URL')),
                ('description', models.CharField(blank=True, default='', help_text='This field sets the global Meta Description tag.', max_length=250)),
                ('header_title', models.CharField(default='My Site', max_length=250)),
                ('header_subtitle', models.CharField(blank=True, max_length=250)),
                ('footer_copyright', models.CharField(default='Simple Personal Site by chrisx8.', help_text='"&copy; YEAR " always shows. Set this to be the text after "&copy; YEAR "', max_length=250)),
            ],
            options={
                'verbose_name': '# Site Info #',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='', help_text='Name of the social media platform', max_length=50)),
                ('username', models.CharField(default='', max_length=100)),
                ('url', models.URLField(default='', help_text='Link to profile page')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'ordering': ['platform', 'username'],
            },
        ),
    ]
