# Generated by Django 2.2 on 2019-05-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='display_at',
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
