# Generated by Django 3.0.3 on 2020-02-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ['platform'], 'verbose_name': 'Social Media Link'},
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='username',
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.URLField(default='', help_text='Link to profile page', verbose_name='URL'),
        ),
    ]
