# Generated by Django 3.0.5 on 2020-04-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0002_auto_20200210_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='site_url',
            field=models.URLField(default='http://example.com', help_text='Include "http://" or "https://". No trailing slashes.', verbose_name='Site URL'),
        ),
    ]
