# Generated by Django 2.2.3 on 2019-07-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0004_auto_20190529_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReCaptcha',
        ),
    ]
