# Generated by Django 2.2.4 on 2019-09-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0005_delete_recaptcha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfig',
        ),
    ]
