# Generated by Django 2.2 on 2019-04-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(default='', help_text='Write in Markdown format', verbose_name='About Me section')),
                ('featured_articles', models.ManyToManyField(blank=True, to='blog.Article')),
                ('featured_projects', models.ManyToManyField(blank=True, to='projects.Project')),
            ],
        ),
    ]
