# Generated by Django 2.2 on 2019-04-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_articles',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_projects',
        ),
        migrations.AddField(
            model_name='homepage',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload resume as a PDF for best compatibility', upload_to=''),
        ),
    ]
