# Generated by Django 2.2.1 on 2019-05-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_me',
            field=models.TextField(blank=True, help_text='Write in Markdown format', verbose_name='About Me section'),
        ),
    ]
