# Generated by Django 2.2 on 2019-04-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190413_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ['-id']},
        ),
    ]
