# Generated by Django 3.1.1 on 2020-09-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='skills',
            field=models.TextField(blank=True, help_text='Write in Markdown format', verbose_name='My Skills section'),
        ),
    ]
