# Generated by Django 3.1.7 on 2021-02-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': '*Site Info*'},
        ),
    ]
