# Generated by Django 5.2.16 on 2026-07-26 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial_squashed_0002_auto_20210222_1759"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmedialink",
            options={"ordering": ("platform",), "verbose_name": "Social Media Link"},
        ),
    ]
