# Generated by Django 3.0.6 on 2020-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('embed_url', models.URLField(default='', help_text='Enter the EMBED URL, not the URL to a webpage.', verbose_name='Embed URL')),
                ('allow_fullscreen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'ordering': ['image'],
            },
        ),
    ]
