# Generated by Django 3.0.6 on 2020-05-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='allow_fullscreen',
            field=models.BooleanField(default=False),
        ),
    ]
