# Generated by Django 5.2.16 on 2026-07-26 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="embed",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ("image",)},
        ),
    ]
