# Generated by Django 2.2.1 on 2019-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('embed_url', models.URLField(default='', help_text='Enter the EMBED URL, not the URL to a webpage.', verbose_name='Embed URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
