# Generated by Django 2.2.1 on 2019-05-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190513_1947'),
        ('media', '0002_embed'),
        ('projects', '0002_auto_20190513_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
