# Generated by Django 3.0.2 on 2020-01-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='alias',
            field=models.CharField(default='', help_text='Example: XYZ is the alias in shortened URL example.com/XYZ', max_length=50, primary_key=True, serialize=False),
        ),
    ]
