# Generated by Django 5.2.16 on 2026-07-26 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0002_alter_url_alias"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="url",
            options={"ordering": ("alias",), "verbose_name": "URL"},
        ),
    ]
