name: build
on:
  push:
    branches: main
  schedule:
    - cron: "0 3 * * 0"
jobs:
  build:
    name: Build Container Image
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: simple-personal-site
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:latest .
      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:latest
      - name: Remove untagged images
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHCR_DELETE_TOKEN }}
          script: |
            const response = await github.request("GET /user/packages/container/${{ env.PACKAGE_NAME }}/versions");
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    const deleteResponse = await github.request("DELETE /user/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                    console.log("[status] " + deleteResponse.status);
                    console.log("Deleted version " + version.id);
                }
            }
