name: build
on:
  push:
    branches: main
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:
jobs:
  build_container:
    name: Build container image
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: simple-personal-site
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:latest .
      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:latest
