---
name: build

on: # yamllint disable-line rule:truthy
  push:
    branches: main
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_container:
    name: Build container image
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.event.repository.name }}
          tags: ${{ env.IMAGE_TAG }}
          containerfiles: ./Dockerfile
      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ github.event.repository.name }}
          tags: ${{ env.IMAGE_TAG }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
