name: build
on:
  push:
    branches: main
  schedule:
    - cron: '0 3 * * 0'
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: chrisx8/simple-personal-site:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t $DOCKER_REPO .
    - name: Run tests
      run: |
        docker run -p 127.0.0.1:8000:8000 --env-file example.env "$DOCKER_REPO" &
        sleep 5
        curl -Lf localhost:8000
    - name: Push image
      env:
        DOCKER_USERNAME: chrisx8
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $DOCKER_REPO
