---
name: test

on: # yamllint disable-line rule:truthy
  push:
    branches-ignore: main
  pull_request:

jobs:
  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
      - name: Run pre-commit checks
        run: |
          uv tool run pre-commit run --all --verbose

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: false
      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt
      - name: Set up project
        run: |
          cp .env.example .env
          python3 manage.py collectstatic --noinput
          python3 manage.py migrate --run-syncdb
      - name: Run tests
        run: |
          python3 -Wa manage.py test
      - name: Test gunicorn server
        run: |
          gunicorn simple_personal_site.wsgi:application -b 127.0.0.1:8000 &
          sleep 3
          curl -Lf localhost:8000
